version: '3.8'
services:
  postgres:
    container_name: lesson-db
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      - POSTGRES_USER=lessondbuser
      - POSTGRES_PASSWORD=pass123456
      - POSTGRES_DB=lessondb
    ports:
      - "5050:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    container_name: lesson-app    
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    ports:
      - "8123:8123"
    environment:
      - PORT=8123
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=lessondbuser
      - DB_PASSWORD=pass123456
      - DB_DATABASE=lessondb
      - DB_TYPE=postgres
    
  
  